### ISSUE TITLE
Some changes to let it work on my devices

### ISSUE THREAD

**Issue by gomez100** [nzfarmer1/mqtt2opcua#1]
Hi!
I successfull tested your code! It works very well, congratulation. I'm an Ignition users too and this is what i did to install your module:
- changed on mqtt2opcua.js the name of OPC UA server from resourcePath: options.opcName || "UA/MQTT Bridge Server" to resourcePath: options.opcName || "UA/MQTT_Bridge_Server" ( Ignition report an error of invalid characters where it founds the space )
- on package.json, under dependecies,  I changed from "Qlobber": "" to "qlobber": "" or npm cannot install all dependencies
- added on mqtt2opcua.js ".toString()" to mqtt publishing ( server.mqtt.publish(message.topic,message.payload.toString()); ). Without the .toString conversion, when a value changed, i wasn't able to receive the topic. I tested with MyMQTT for Android and MqttFx. Now it works perfectly.
- What do you think about the opportunity to add logging features on database of received topic and add a parsing for "json formatted" payload?

Best regards, Andrea.

**Comment by nzfarmer1** [comment]
Hi Andrea

All changes sound reasonable. Please send me your copy so I can apply.

Have thought about a database persistence layer, but no firm conclusions.

Might be that there is a plugin framework like Mosca uses ..?

Welcome your thoughts.

Andrew

Please consider the environment before printing this email.

Any information contained within this email is for the use of the recipient only and is sent in confidence. The information may not be copied, distributed or forwarded to any other parties. This information may not be used by any other person or organization. If you have received this in error, please notify us immediately by return mail and return the message with your notification.

If you would like to stop receiving correspondence from this email address, please confirm by return mail.

**Comment by gomez100** [comment]
Hi,
how can attach a js file? do you prefer i send it directly to your email? Let me know! Did you already see mqttwarn? I'm thinking to DB storage and payload jsoned to retrieve lost data, so you can send value and timestamp directy to a database!
Best regards, andrea.

**Comment by nzfarmer1** [comment]
> how can attach a js file? do you prefer i send it directly to your email? Let me know! Did you already see mqttwarn? I'm thinking to DB storage and payload jsoned to retrieve lost data, so you can send value and timestamp directy to a database!
> Best regards, andrea.
> 
> —

Good idea. I am andrew@agsense.co.nz.

Looking at mqttwarn now ...

**Comment by nzfarmer1** [comment]
I've added toString casting for the handler topic and payload.  The run.js example has been updated to show how you can change the resource name of the OPC server in your own scripts (i.e. if underscores are required).  They don't seem to be on OSX.

Have also added a roundtrip flag so that if you want to force a roundtrip verification that the OPCUA SET has worked, you can.

See 0.0.10

**Comment by gomez100** [comment]
I  thought maybe it can depend on which version of java ignition is running.

2015-07-30 22:07 GMT+02:00 Andrew McClure notifications@github.com:

**Comment by gomez100** [comment]
Hi Andrew!!
I'm testing on my pc your last release! Perfectly nice working, no modify
to do to let it works, only topic and server! I'm testing it with an
ESP8266 with lua loader and mqtt client, data are arriving but i received
this warning:
[image: Immagine incorporata 1]
Do you have any idea? Ignition seems to work without problem. Did you
already thing to add to your code a last will testament to check of the
remote mqtt client is alive and if not put bad quality on OPCua tag? best
regards!

2015-07-31 9:12 GMT+02:00 Andrea Balboni me.balboni@gmail.com:

**Comment by nzfarmer1** [comment]
Could it be related to OPCUA authentication?  There was warning prompt that came up when I tested it on UA Explorer about a lack of certificate - but then it worked fine.

**Comment by gomez100** [comment]
I'll test it and i'll let you know!
Anyway, about your work that it's very interestening, i'd like to suggest
you some other low payload protocol implementation instead mqtt-sn. By
using some nrf24l01 instead xbee or hoperf 868 and so on, a good
implementation is in myopionion mysensors.org, API 1.5! Give it a check!
It's simple serial protocol with a lot of example to port it in modbus or
mqtt with arduino, php and so on. The library work also as sensor node or
repeater.  I'd like to test also but i didn't but it yet
http://www.anarduino.com/miniwireless/ that's is low cost, with storage
space to log data ( i.e. value+timestamp ) rtc clock. It support some good
library like http://www.airspayce.com/mikem/arduino/RadioHead/

2015-08-03 21:41 GMT+02:00 Andrew McClure notifications@github.com:

**Comment by nzfarmer1** [comment]
Thanks.   We have looked at RadioHead (not an MIT license and less efficient meshing than XBee from what I recall?)

If MQTT-SN issues are not resolved soon our first option is to explore a simpler alternative using perhaps svd-xbee and xbee-api for arduinio.

**Comment by gomez100** [comment]
Hi Andrew,
did you already see LoRa tecnology? Just a question....suppose you're
receiving data from an mqtt client, like xx/led_1, where the status is sent
with 1 that means led is on and 0 led is off,  and you also subscribe to
xx/led_1 to receive command like 1 to switch it on or 0 to off from scada (
i.e. ignition ) what's is gonna happend? You will have twice traffic
because the sent command is re-read from the client. Is there a solution in
your opinion?? Did you planned to insert secuirty in your script ( mqtt
side ? )
Best regards and thanks in advance for your suggestion!!!

2015-08-04 17:42 GMT+02:00 Andrew McClure notifications@github.com:

**Comment by nzfarmer1** [comment]
Hi Andrea

Am aware of the use case you describe.  One solution is to use different topics.  For example, append 'update' to the topic when changing a value.  A state machine can also help, where you have states of ON, SwitchingOFF, OFF, SwitchingON etc.

LORA looks really interesting.  It is lower cost than the XBee but uses a little more power due to the length of the transmission cycle whereas our focus has been on reducing power consumption.  For us it's also a question of time as the XBees work and we have a good knowledge of them.

Anyway, I'll code this issue. Feel free to contact me in person!
