### ISSUE TITLE
Error when perform npm link

### ISSUE THREAD

**Issue by kusumy** [nzfarmer1/mqtt2opcua#4]
I've try to follow the instruction installing the mqtt2opcua. 
But there are  errors when performing npm link.
However OPC UA is running when i perform node examples/run.js ( i can see it on the Ignition). 
But i can not see my mqtt topics on the OPC UA Client, only see a Server node.
The module is connected to MQTT broker. 
I have topics on the broker:
     modsim/40000 and modsim/40001

I have Node version 7.2.0, npm version 3.10.9.

I attached the run.js of my example, and the npm link log.

[mqtt2opcua_log.zip](https://github.com/nzfarmer1/mqtt2opcua/files/651354/mqtt2opcua_log.zip)

**Comment by nzfarmer1** [comment]
Hi, It's a little hard for me to troubleshoot remotely as I don't have your setup. I may be able to Teamview in and take a look. Pls contact me direct: andrew@agsense.co.nz
