### ISSUE TITLE
Only one OPC item is created

### ISSUE THREAD

**Issue by jhottell** [nzfarmer1/mqtt2opcua#6]
I have been working on this for a few days, no matter what I do it only adds the first MQTT Topic to the OPC server but no more. Am I doing something wrong? It keeps saying "No handler defined" for any additional topics and never adds them.

![image](https://user-images.githubusercontent.com/5099859/29467277-7ccf8020-8405-11e7-80a8-c56398d8d150.png)
![image](https://user-images.githubusercontent.com/5099859/29467287-83a0537a-8405-11e7-926d-82b83aaf987d.png)

Thanks for any help!

**Comment by nzfarmer1** [comment]
Sorry, I only just saw this. Are you still having issues?

**Comment by jhottell** [comment]
Yes this is still an issue for me

**Comment by nzfarmer1** [comment]
How have you defined your forward handlers?

Perhaps use:
forward.on("Test1/#", function(payload) {  ...
