### ISSUE TITLE
Created empty folders, no opc items

### ISSUE THREAD

**Issue by yonas124** [nzfarmer1/mqtt2opcua#7]
I tried to subscribe to a device on Ubidots with 2 variables. It successfully created folders but not opc items.

Responses are:
/v1.6/devices/yonaspc/var1 : msg.payload : string[92]
"{"timestamp": 1534670851674, "context": {}, "value": 22.1, "id": "5b7938035916366f6124b56f"}"

/v1.6/devices/yonaspc/var1/lv : msg.payload : string[4]
"22.1"

I used the function in folder examples. Please advise.

**Comment by nzfarmer1** [comment]
HI, sorry just noticed this. Are you still having issues?

**Comment by nzfarmer1** [comment]
No feedback
